# Generated by Django 4.2.2 on 2023-06-27 23:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('libreria', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='libro',
            name='fecha_actualizacion',
        ),
        migrations.RemoveField(
            model_name='libro',
            name='fecha_creacion',
        ),
    ]
